create table if not exists public.market_prices (
  id bigint generated by default as identity primary key,
  trade_date date not null,
  symbol text not null,
  close numeric not null,
  currency text not null default 'USD',
  source text not null default 'yfinance',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (trade_date, symbol, source)
);

create table if not exists public.exchange_rates (
  id bigint generated by default as identity primary key,
  rate_date date not null,
  pair text not null,
  rate numeric not null,
  source text not null default 'yfinance',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (rate_date, pair, source)
);

create table if not exists public.simulation_snapshots (
  id bigint generated by default as identity primary key,
  run_date date not null,
  scenario_label text not null,
  owner_id text not null check (owner_id in ('self', 'spouse', 'couple')),
  total_assets numeric not null,
  tqqq_value numeric not null default 0,
  qld_value numeric not null default 0,
  qld_cash_value numeric not null default 0,
  spym_value numeric not null default 0,
  boxx_value numeric not null default 0,
  cumulative_withdrawal numeric not null default 0,
  strategy_state text,
  created_at timestamptz not null default now(),
  unique (run_date, scenario_label, owner_id)
);

alter table public.market_prices enable row level security;
alter table public.exchange_rates enable row level security;
alter table public.simulation_snapshots enable row level security;

drop policy if exists "Public read market prices" on public.market_prices;
create policy "Public read market prices"
on public.market_prices for select
to anon, authenticated
using (true);

drop policy if exists "Public read exchange rates" on public.exchange_rates;
create policy "Public read exchange rates"
on public.exchange_rates for select
to anon, authenticated
using (true);

drop policy if exists "Public read simulation snapshots" on public.simulation_snapshots;
create policy "Public read simulation snapshots"
on public.simulation_snapshots for select
to anon, authenticated
using (true);
